kind: Deployment
apiVersion: apps/v1
metadata:
  name: mssql-deployment
  labels:
    app: mssql-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mssql-deployment
  template:
    metadata:
      labels:
        app: mssql-deployment
    spec:
      containers:
      - name: mssql-deployment
        image: mcr.microsoft.com/mssql/server:2017-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "dinesh#01"
        - name: MSSQL_PID
          value: "Express"
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql-deployment
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
